remote_theme: pages-themes/primer@v0.6.0
layout: default
title: >
    The ultimate PyCharm plugin that every Odoo developer needs.
    Stop wasting time editing configs and typing long commands.
    Instantly switch databases, pick modules, and run tests with powerful smart macros — all with one click.
    Fast database selector, smart module picker, automatic run configurations, and a powerful context menu that makes development actually enjoyable.
    Develop faster. Switch smarter. Get shit done.
url: "https://bts-odoo-selector.com"
image: /images/BTS.jpg
logo: /images/BTS.jpg
